#!/usr/bin/bash
#
# ALIS — Arch Linux Install Script
#

start_system_installation(){
  msg "Get ready to rock!"
  sleep 500
  pre_install
  create_partitions
  core_system
  copy_configs
  setup_systemd_in_chroot
#  setup_bootloader
}

show_usage(){
  printf "%s\\n" "Here will be a help pages"
}

msg(){
  printf "%s\\n" "$@" >&2
}

die(){
  printf "%s\\n" "$@" >&2
  exit 1
}

parse_args(){
  for argument in "$@"
  do
  case $argument in
    install)
    action=start_system_installation
      shift
      ;;
    -h|--help)
    action=show_usage
      shift
      ;;
    -v |--verbose)
      set -o verbose
      printf "%s\\n" "Verbose mode enabled"
      shift
      ;;
    *)
      msg  "Unknown argument $argument"
      ;;
  esac
  done
}

import_libs(){
  source libs/pre_install.sh
  source libs/create_partitions.sh
  source libs/core_system.sh
  source libs/copy_configs.sh
  source libs/setup_systemd_in_chroot.sh
}

check_deps(){
  if [ ! -d "$script_name"_libs ]; then
        mkdir "$script_name"_libs
        cd "$script_name"_libs
        for dep in ${script_deps[*]}
        do
          curl --retry 3 --retry-delay 2 -O "$dep"
        done
        echo
  fi
}

check_vars(){
  readonly luks_header="header.img"
  readonly luks_keyfile="crypto_keyfile.bin"
  readonly luks_device="arch"
   readonly mountpoint="/mnt"
    readonly luks_uuid="04c2b973-4aca-45e6-8434-f66ed6ea922d"
      readonly os_uuid="1232b973-4aca-45e6-8434-f66ed6ea9321"

      esp_label=${esp_label:-ESP}
       esp_part=${esp_part:-/dev/sda1}
  esp_part_opts=${esp_part_opts:-rw,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro}

      os_label=${os_part_label:-OS}
       os_part=${os_part:-/dev/sda2}
  os_part_opts=${os_part_opts:-defaults,noatime,compress=lzo,space_cache,commit=120}
        cipher=${cipher:-aes-xts-plain -s 256}

        action=${action:-show_usage}
  country_code=${country_code:-RU}
}

init(){
   readonly script_name='alis'
   readonly script_desc='Arch Linux Install Script'
   readonly script_repo='https://github.com/alis-repo/alis'
   readonly script_deps=('checkinstall.sh' 'storage.sh' 'packstrap.sh' 'configs.sh')
   readonly script_filename="${0##*/}"
   readonly script_path="$(cd "$(dirname "$0")" && pwd)"
}

main(){
  set -o errexit                #let script exit if a command fails
  set -o nounset                #let script exit if an unsed variable is used
  set -o pipefail               #let script exit if any command in a pipeline fails
  set -o vi                     #let script use vi-style cpmmand line editing interface
  set -o posix                  #let script use the behavior of bash for POSIX
# set -o xtrace                 #let script show value of PS4 after expanding each command

  IFS=$'\n\t'                   #set word splitter to new line and tab

  init                          #get path, description and dependencys for this script.
  parse_args "$@"               #parse arguments passed to script via command line
  check_vars                    #check for unset or null vars and apply default values.
  check_deps                    #check and resolv deps for this csript
  "$action"                     #start default or passed by user type of action
}

main "$@"                       #enter point

