#!/usr/bin/bash
#
# ALIS — Arch Linux Install Script
#
set -euo pipefail
IFS=$'\n\t'

title(){
  title_decor=" >"
  printf "%s\n" "$title_decor $@" >&2
}

msg(){
  msg_decor="   +"
  printf "%s\n" "$msg_decor $@" >&2
}

die(){
  die_decor="   -"
  printf "%s\n" "$die_decor $@" >&2
  exit 1
}

import_libs(){
  . libs/pre_install.sh
  . libs/create_partitions.sh
  . libs/min_pack.sh
  . libs/copy_configs.sh
  . libs/setup_systemd_in_chroot.sh
  . libs/setup_bootloader.sh
}

show_settings(){
 printf "%s\n" "Here current settings"
}

import_config(){
. "$config"
}

start_configuration(){
  printf "%s\n" "Lets tune this shit!"
}

show_usage(){
  printf "%s\n" "Here will be a help pages"
}

show_status(){
  printf "%s\n" "New OS ready to install"
}

start_system_installation(){
  title "Get ready to rock!"
  pre_install
  create_partitions
  min_pack
  copy_configs
  setup_systemd_in_chroot
  setup_bootloader
}

parse_arguments(){
  for argument in "$@"
  do
  case $argument in
    install)
    action=start_system_installation
      shift
      ;;
    status)
    action=show_status
      shift
      ;;
    setup|config|configure)
    action=start_configuration
      shift
      ;;
    -h|help)
    action=show_usage
      shift
      ;;
    --esp_label=*)
      esp_label="${argument#*=}"
      shift
      ;;
    --esp_part=*)
      esp_part="${argument#*=}"
      shift
      ;;
    --esp_part_opts=*)
      esp_part_opts="${argument#*=}"
      shift
      ;;
    --os_label=*)
      os_label="${argument#*=}"
      shift
      ;;
    --os_part=*)
      os_part="${argument#*=}"
      shift
      ;;
    --os_part_opts=*)
      os_part_opts="${argument#*=}"
      shift
      ;;
    --cipher=*)
      cipher="${argument#*=}"
      shift
      ;;
    -v |--verbose)
      set -x
      verbose_mode="true"
      printf "%s\n" "Verbose mode enabled"
      shift
      ;;
     --config=*)
      config="${argument#*=}"
      import_config
      shift
      ;;
    *)
      printf "%s\n"  "Error"
      ;;
  esac
  done
}

set_defaults(){

  readonly luks_header="header.img"
  readonly luks_device="arch"
   readonly mountpoint="/mnt"
    readonly luks_uuid="04c2b973-4aca-45e6-8434-f66ed6ea922d"
      readonly os_uuid="1232b973-4aca-45e6-8434-f66ed6ea9321"

      esp_label=${esp_label:-ESP}
       esp_part=${esp_part:-/dev/sda1}
  esp_part_opts=${esp_part_opts:-rw,noauto,x-systemd.automount,noatime,fmask=0022,dmask=0022,codepage=866,iocharset=utf8,utf8=true,shortname=mixed,errors=remount-ro}

      os_label=${os_part_label:-OS}
       os_part=${os_part:-/dev/sda2}
  os_part_opts=${os_part_opts:-defaults,noatime,compress=lzo,space_cache,commit=120,noauto,x-systemd.automount}
        cipher=${cipher:-aes-xts-plain -s 256}


        action=${action:-show_usage}
  verbose_mode=${verbose_mode:-false}
        config=${congig:-configs/etc/alis/alisrc}
  country_code=${country_code:-RU}
}

main(){
  clear
  set_defaults
  import_config
  import_libs
  parse_arguments "$@"
  "$action"
}

main "$@"